services:
  daily:
    build:
      context: .                 # repo root (so .dockerignore applies)
      dockerfile: docker/Dockerfile
    command: python -m src.pipelines.daily
    environment:
      - TZ=Australia/Sydney
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
